### ISSUE TITLE
Use Calendar App as CalDAV-Client for non-ownCloud CalDAV Servers

### ISSUE THREAD

**Issue by aspdye** [owncloud/calendar#104]

**Comment by georgehrke** [comment]
Not a priority at all at the moment.

**Comment by georgehrke** [comment]
What would be a use case anyway?

**Comment by aspdye** [comment]
E.g. using Google Calendar inside of ownCloud ;)

**Comment by amandabee** [comment]
Use case:

User has a personal OwnCloud instance where she keeps her own calendar, shared household calendars. User also works at an organization that uses Google enterprise and so maintains a Google calendar at work. On an Android device, CalDav sync means she can access all of her calendars in a single calendar interface. At her desk, however, she has to compare tabs to get a full picture of her calendar, because there's no way to access both in a single interface.
