### ISSUE TITLE
make sure an eventSource is added only once to fullcalendar

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#213]

**Comment by georgehrke** [comment]
That's actually a tough one.
Calling addEventSource, removeEventSource and eventSource immediately one after another, it renders the calendar twice.
```js
fc.fullCalendar('addEventSource', scope.eventSource['/remote.php/dav/calendars/admin/uni/']);
fc.fullCalendar('removeEventSource', scope.eventSource['/remote.php/dav/calendars/admin/uni/']);
fc.fullCalendar('addEventSource', scope.eventSource['/remote.php/dav/calendars/admin/uni/']);
```

@arshaw Sorry for mentioning you directly here, but do you consider this a bug in fullcalendar?
If yes, I'll file a proper bug report in the fullcalendar repo.
(We use eventSources with `events: function (start, end, timezone, callback)`)

**Comment by georgehrke** [comment]
Note to myself if not considered a bug in fullcalendar:
an event source may have arbitrary properties, just add an `isRendering` property and don't call addEventSource if it's true.

**Comment by arshaw** [comment]
i don't consider this a bug, because some ppl might expect the events to render+unrender+render if you consider these atomic operations. when i see people doing this, they're usually doing it the wrong way. they should be calling `refetchEvents` instead.

this is an optimization that, when implemented, will help you:
https://github.com/fullcalendar/fullcalendar/issues/2938
