### ISSUE TITLE
if a reminder with 15 mins before already exists, create one with 30 minutes before and so on

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#307]

**Comment by marneu** [comment]
### Wishlist
1. add a daily cron task form a daily email reminder on all events (own+shared)
3. make reminders/notifications on a per user setting

### Expected behaviour
A german example for the daily reminder on 8.x installations can be found here https://www.std-soft.com/hm-service/code/23-kalender-notifikation-fuer-owncloud

**Comment by georgehrke** [comment]
> Wishlist
> 
> add a daily cron task for a daily email reminder on all events (own+shared)
> make reminders/notifications on a per user setting

If anything, please create dedicated issues and don't just comment on other issues with your feature requests. Additionally starting with ownCloud 9 the calendar app is just a GUI. Everything related to the server belongs in core.

> A german example for the daily reminder on 8.x installations can be found here

Won't work with 9.0+

**Comment by marneu** [comment]
> Won't work with 9.0+
> I know + removed
