### ISSUE TITLE
Sorting of calendars

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/calendar#394]
Currently calendars are sorted alphabetically (right?). This results in my »Events« calendar being sorted before by more important »Personal« calendar. Also, it is used as the default calendar in the new event dropdown which is not correct.

How about changing this to sorting the calendar by usage, that is amount of events in it? Would be a bit of guessing, but might fit better for many cases than alphabetical. Also we don’t need to bother with a »default calendar« setting that way.

What do you think @georgehrke?

**Comment by georgehrke** [comment]
I would still prefer to just make the calendar list sortable. I don't think it should be too complex to implement this and it fulfills all needs.
iCloud calendar does this as well.

Both usage and amount of events would increase the number of requests to the caldav server dramatically.

**Comment by j-ed** [comment]
Wouldn't it be possible to allow users to individually sort calendars similar as it has been possible in the tasks app in the past? I don't like automated sorting because every users may have a different way how he works and how he wants to get the calendars displayed.

**Comment by georgehrke** [comment]
@j-ed That's exactly what I mean with 'make the calendar list sortable' :wink:

**Comment by zeugmatis** [comment]
Currently they are listed in order added.  I would _really_ like to see a simple alphabetical sort if possible - this way, we can have multiple calendars which are named by e.g. usernames, real names, or company names etc. and we have an intuitive way for anyone to quickly look them up.  If you want to make sure a calendar is listed at the top, just hack the calendar name.  A bit ugly but far less complicated.  Either that or maybe buttons like in the galleryplus app but really I think a simple alphabetical a-z sorted listing would help a whole lot.

**Comment by hitam4450** [comment]
I agree on that issue, an would like to see something like that - maybe in the next release already!

regards, hitam4450

**Comment by zeugmatis** [comment]
Can someone here please let us know where the SQL for this is, so one of us can add the "ASC" to the query.  I think that we should all agree on this and get it into the source, I am not interested in a "one-off" approach and we should all share the code.  Greetings from California.

**Comment by georgehrke** [comment]
@zeugmatis in core, please ask on free node in owncloud-dev

**Comment by georgehrke** [comment]
> would like to see something like that - maybe in the next release already!

WTF? 
Check your privileges! You are not in a position to make any demands. 
This is free software. If you want a feature, implement it.

And as this is not the first issue:
- If you like a feature request, don't leave useless comments, use reactions: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
- If you want a feature to be implemented earlier, then implement it, but you are the last one here to make any demands.

**Comment by zeugmatis** [comment]
I feel sad for your your mother, who probably would always expect better from you.  

Anyway, my point was only a suggestion that people could be human and help each other, thus entertain the thought of having something better.  Why are are you acting like such a goddam asshole?  Is it because you don't know how to fix it?

**Comment by zeugmatis** [comment]
Hollly shit I just got it.  hahaaaa you got me!  :-D

**Comment by zeugmatis** [comment]
Games on you now.  That was awesome.  :-D

**Comment by georgehrke** [comment]
hehe, @zeugmatis that comment wasn't meant for you :wink:

It's currently ordered by the calendar order property. 
see https://github.com/owncloud/core/blob/master/apps/dav/lib/caldav/caldavbackend.php#L155

**Comment by zeugmatis** [comment]
Thanks mate.  This helps a lot.

Push it in, thanks again -

Mark

—
Syminet Internetworking Solutions
https://secure.syminet.com/
1-949-379-8472 ext. 8049
GPG: 2048R/966057BB

**Comment by georgehrke** [comment]
@zeugmatis I just remembered that we sort it in the calendar again.
See https://github.com/owncloud/calendar/blob/master/templates/part.calendarlist.php#L27

Replacing `order` with `displayname` would sort the calendars alphabetically, but I would still prefer to just make the calendar list sortable.

**Comment by georgehrke** [comment]
There is also an issue about making the calendar list sortable: https://github.com/owncloud/calendar/issues/133

@jancborchardt What's your call on this?
I would prefer to just make it sortable. It's intuitiv, it fulfills all needs, it's reflected everywhere the user sees a list of calendars. We could add some CSS `cursor` on the list items to improve discoverability.

**Comment by zeugmatis** [comment]
Agreed.  The reason I’m here is because people need ~200 calendars, we should be able to at least list them sorted alphabetically on the left side..,

Wanting to sell ownclud, basic things like this make a huge difference - cannot sell it without reliability and some basic things like this!  :-)

Mark

**Comment by zeugmatis** [comment]
LOL it’s totally fine with “privileges”, I actually laughed a lot at that!

Sorry but I too find the following regarding the US President election to be
utterly HILARIOUS:

https://www.reddit.com/r/the_donald

LOL, if we have to put up with it… may as well have fun with it!

Anyway thank you, I’ll look at the code - I think all we need is a “sort ASC”
in the query?  Or however the best way we should do it.  And then we should
be all good.

Simple alphabetical sort, so that anyone can find them.  :-)

Best -

Mark

**Comment by georgehrke** [comment]
> people need ~200 calendars

Now I'm curious. What's the use case here?
I'd guess that the average user has not more than 5 calendars. Power users might have up to 30 (including shared ones), but 200?

**Comment by zeugmatis** [comment]
Sure.  Say I am the "appointments secretary" at a large law firm with 50 attorneys, and their case load is ~4 cases each with a calendar for each case.  The attorneys are busy, and only want readonly access to their calendars via their native phone/tablet apps.  They do not care about any other aspect of how it works.  

I create each calendar named in the form of "$attorney_name - $client_name" and that calendar is then shared by me to their owncloud account (I'm the actual owner of all of the calendars).  

When they are sorted by date added, you get an increasingly random list as completed cases get removed, and new cases are added.  When sorted alphabetically, I can quickly grab the scrollbar and drag to where I need - _much_ more easy and intuitive.  

I guess too it's a bit like file listings.  The owncloud Files app and even the 'ls' command has by default always sorted alphabetically, because it's intuitive to rapidly find what you need.  Imagine if the 'ls' command defaulted to 'ls -U'... 

Users could then also control things a bit by e.g. putting an 'a' as the first letter in a name to force a calendar to the top.  Ugly I know!  :-)  But at least the option is there.

**Comment by zeugmatis** [comment]
Another example.  What if you're a nurse who's paid to help old people.  There is a person at the office who takes appointments via phone (and old people use the phone).  As the "checker-person" you need to be there at a certain time.  

Again, we have a case with ~200 calendars for the "administrator".   

This is real-world use of technology and I think people should listen.

**Comment by georgehrke** [comment]
closing in favor of https://github.com/owncloud/calendar/issues/133

**Comment by zeugmatis** [comment]
Well what about managing a nursing home?
