### ISSUE TITLE
add proper indication if a calendar was shared

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#431]
change the opacity to something higher and add `Shared` label

**Comment by MathieuSchopfer** [comment]
I could take care of this.
@georgehrke :
- By "change the opacity", do you mean the opacity of the share icon ?
- How would see an extra `Shared` label ? Just some styled plain text near the calendar name ?

**Comment by MathieuSchopfer** [comment]
It could be something like this :
![capture du 2016-06-02 22 03 08](https://cloud.githubusercontent.com/assets/17726101/15759341/995a7af4-290e-11e6-94da-ad5a5f79ede9.png)

**Comment by georgehrke** [comment]
Thanks a lot for your interest in contributing to the calendar! :)
The behavior concerning "Shared" label and opacity should be the very same as in core.

Concerning the logic:
You can probably very easily implement this by extending the calendar model with a function that checks if the calendar is shared, and using ng-if for label and ng-style for the opacity.

**Comment by MathieuSchopfer** [comment]
The logical test in the calendar prototype could be `this.sharedWith.users.length > 0 || this.sharedWith.groups.length > 0`. I am just not sure how safe this is, because the `sharedWith` attribute is not declared in the calendar model (it seems to be added by the calendar service).

Concerning the rendering :
1. `core` provides two styling classes, `icon-share` and `icon-shared`, and two (possibly) different icons. So I used `ng-class` to adapt the class conditionally and thus get the correct icon.
2. I am not sure it is (ever) a good idea to use inline CSS rules. So, instead of applying a dynamic style with the `ng-style` directive, we could create a new class in the existing CSS template (named e.g. `withitems`) and apply it conditionally with `ng-class` again.
3. I can't get to add cleanly the `Shared` label after the icon. It seems there is a clash with the `action` class style. See the screen-shot below.

![capture du 2016-06-03 15 46 06](https://cloud.githubusercontent.com/assets/17726101/15780534/79c8debc-29a2-11e6-92ae-85f85c90b8c9.png)

Finally, I don't think I can push to this repository.

**Comment by MathieuSchopfer** [comment]
Ok, so I managed to fix the last issue by adding some styling rules to the label.
@georgehrke I would like to push my code to a new branch, but I am not granted the access to the calendar repository. What should I do ?

**Comment by raimund-schluessler** [comment]
For getting access to the repo you need to sign the CLA I think. But you can also just push to your private repo and create a PR form there.
