### ISSUE TITLE
Events without summary

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/calendar#568]
How could I allow events without summary? Is there any option in the config or which file I have to change?

**Comment by georgehrke** [comment]
> How could I allow events without summary?

Not at all.

> Is there any option in the config or which file I have to change?

No, there is not.

What's the use case?
Creating an event without a title seems pretty useless to me.

**Comment by georgehrke** [comment]
If you want more privacy in shared calendars, ownCloud 9.1 will introduce an option to hide or show an event only as busy when shared.

**Comment by scriptPilot** [comment]
Use case: I have a calendar only for working times. So what count is only the start/end time for further proceeding. Where is the block so that I could enable it maybe only for my ownCloud installation?

**Comment by georgehrke** [comment]
> I have a calendar only for working times. So what count is only the start/end time for further proceeding.

Simply call it `Work`? 😉

Anyway, there you go: https://github.com/owncloud/calendar/blob/master/js/app/controllers/editorcontroller.js#L110

But I would really like to discourage you from removing this check, as it makes both of our lives more difficult. You have to patch every release of the calendar and make sure it will always work with latest version and I could have difficulties reproducing your bug reports because it might work just fine without your patch.

**Comment by scriptPilot** [comment]
Thank you! :-)
