### ISSUE TITLE
UI for calendar on a mobile device has event dialog box under everything else

### ISSUE THREAD

**Issue by ericcotelnu** [owncloud/calendar#703]
Hi,

I have a very hard time editing/adding an event from a mobile device as the CSS makes the dialog box disappear under the calendar, but not the sidebar. I think the z-index is totally wrong. I consider this a serious issue. I also get this in other browsers, not just Firefox.

**Comment by jancborchardt** [comment]
@ericcotelnu thank you for the report! Please review the fix at https://github.com/owncloud/calendar/pull/737

You can also mention me by using @jancborchardt whenever you find an interface issue – then I will see it faster. Or since you seem to know how to fix that stuff you are also welcome to make pull requests of your own in the future. :)
