### ISSUE TITLE
OC8 - Delete only one event from a repeating

### ISSUE THREAD

**Issue by Nocxelp** [owncloud/calendar#709]
Now i can only delete the hole event repeating and not one of for exaple ten.
Please make it possible.

For example:
I have a event that is on every monday. But on my holiday a dont want to have this event....

thanks,
Nocxelp

**Comment by georgehrke** [comment]
duplicate

**Comment by georgehrke** [comment]
please search for existing bug reports / feature requests before creating new issues

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/calendar/issues/67 as searching for "repeating" or "recurring" don't lead to this duplicate.

**Comment by layerzerolabs** [comment]
Of course we should all search for issues before creating new ones. But it is hardly surprising to find this issue keeps being raised as it's been open for over two years and two versions, every few months someone opens an issue for it. #23 #33 #78 #448 #456 #507 #670 #709 Perhaps this is a sign that it is an important feature? given that users have been continuously requesting it for over two years? As one user commented in 2013 - This is an absolute NO-GO. A Calendar which cannot handle regular Events - and Exceptions are a vital part of it - is completely useless.

for what it's worth, accessing the calendar over caldav from my phone allows deleting of events from the middle of a repeating series. not sure if this causes problems inside owncloud.

I'm trying to persuade my friends to use this open source calendar rather than google - this isn't helping!!! In fact, if I din't have a way of getting around the bug with my phone, I'd ditch it myself.
