### ISSUE TITLE
OC8 - Create a group Calendar

### ISSUE THREAD

**Issue by Nocxelp** [owncloud/calendar#711]
for example: a group with 5 users.
so you can create a groupview in the calendar. Only one calendar with all users.

thanks,
nocxelp

**Comment by georgehrke** [comment]
there is calendar sharing and you can give everyone full rights, no need for dedicated group calendar feature.

**Comment by Nocxelp** [comment]
no I mean....
everyone have a own calendar and there is one calendar with the events from a group.
and in this group calendar are all event automatic from the hole group.

**Comment by georgehrke** [comment]
what's the usecase?

**Comment by georgehrke** [comment]
and still: how is your proposal superior to simply sharing a calendar?

**Comment by georgehrke** [comment]
and who should see this group calendar?

**Comment by Bullnados** [comment]
Usecase for example: familiy calendar, where everybody can add new entries. Would be much easer than share every single entry.

**Comment by georgehrke** [comment]
> familiy calendar

@Bullnados How would a group calendar be superior over simply one family member sharing a calendar with a family group?

**Comment by Bullnados** [comment]
At the moment you need a external programm for editing a shared calendar aren't you?
Perhaps familiy wasnt a good example, because you could install the external programms.
For our purpose(club with 5 chairmans, changing every year) its much easer to config owncloud and than they can edit all in owncloud.(Mail, calendar, tasks, contacts). The problem is, that they dont use Outlook or Thunderbird, they only use webbased services.

**Comment by georgehrke** [comment]
Why external program? You can edit shared calendars via web-interface or caldav. No external programs required

**Comment by georgehrke** [comment]
> For our purpose(club with 5 chairmans, changing every year)

Just create a group in the user management, add all 5 chairmans, create a calendar in the admin account, share it with the group, problem solved ;)

**Comment by Bullnados** [comment]
Thanks :smile: 
Sometimes you miss the forest for the trees.
But the problem is i didnt see the symbol for that. Neither FF nor Opera.
I created a user and add him to a group. Im just in admin group.
![unbenannt](https://cloud.githubusercontent.com/assets/11041576/8656717/9a4397a4-2999-11e5-9e56-e49332d87264.PNG)

**Comment by georgehrke** [comment]
Is adblock enabled in your browser? I sharing enabled in the admin settings?

**Comment by Bullnados** [comment]
Yes and thanks again :smiley:
