### ISSUE TITLE
Better readability of calendar entries

### ISSUE THREAD

**Issue by scroom** [owncloud/calendar#723]
### Steps to reproduce
1. Use the calendar app and use the weekly view
2. Add an entry with a quite long title which lasts some hours
### Expected behaviour

The title of the calendar entry should be visible and if necessary a wordwrap should be used.
### Actual behaviour

Just the part of the title of the calendar entry which fits into one row is visible. Here comes a screenshot to clarify what I mean (used fantasy-title is: Projektleitertreffen der Leiter der 5. Klassen):
![bildschirmfoto vom 2016-08-30 12-34-41](https://cloud.githubusercontent.com/assets/5347731/18086033/3040ae40-6eae-11e6-9b05-a7a8c7ba3586.png)
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Server version:** 9.0.4
**Calendar version:** 1.3.3

Do you need more information?

**Comment by georgehrke** [comment]
- ~~[ ] has to be reported upstream~~

**Comment by georgehrke** [comment]
<img width="744" alt="fullcalendar - javascript event calendar jquery plugin safari technology preview today at 9 56 57 pm" src="https://cloud.githubusercontent.com/assets/1250540/18288717/e3e73256-747c-11e6-9dcf-93fee19d5015.png">

Apparently this issue is not reproducible on the latest full calendar version.
Either we are overwriting some CSS rule or this has been fixed with fullcalendar 3.
We are currently running fullcalendar 2.x, but will update really soon.

**Comment by georgehrke** [comment]
<img width="169" alt="calendar - nextcloud chromium today at 12 07 27 am" src="https://cloud.githubusercontent.com/assets/1250540/18292752/25de5ee8-748f-11e6-8d4f-82307a81d11c.png">
It has nothing to do with fullcalendar 3, it's related to the `white-space:no-wrap` in core's style.css
