### ISSUE TITLE
CLI backups of contacts (cardDAV) not working in ownCloud 8.0.0

### ISSUE THREAD

**Issue by ontheair81** [owncloud/calendar#738]
Hello,

I am running a cronjob every night to backup the cardDAV contacts / addressbook to a .vcf-file on my server. This was working very well with prior versions of ownCloud, but it is not working since upgrading to ownCloud 8.0.0.

This is the command of the cronjob:
wget --auth-no-challenge --no-clobber --http-user=[USERNAME] --http-password=[PASSWORD] -O [LOCAL/PATH/TO/STORE/VCF]`date +\%Y\%m\%d`-MyContacts.vcf "http://localhost/owncloud/index.php/apps/contacts/addressbook/local/18/export"

The command now returns this error:
HTTP-Anforderung gesendet, warte auf Antwort... 500 Internal Server Error
2015-02-23 08:24:13 FEHLER 500: Internal Server Error.

The webserver log shows an Error 500 also.

But when I visit this URL with a browser, I can log in and download the .vcf-file:
http://myserver.net/owncloud/index.php/apps/contacts/addressbook/local/18/export

Also everything else is working. Just the backup via command line is not working.

This was discussed and confirmed by another user in the ownCloud-Forums:
https://forum.owncloud.org/viewtopic.php?f=31&t=26640&p=80594#p80594

(This is my first issue in GitHub, so sorry if I missed some information needed. In this case just reply and I will do my best.)

**Comment by georgehrke** [comment]
wrong repo ;)
please reopen in the contacts repo

**Comment by georgehrke** [comment]
please use the issue template when reopening this in the contacts repo, at least provide server error logs

**Comment by Angie45** [comment]
I never used this Software. Currently I am using Ahsay backup solution. CloudBacko is one of the local backup software for MySQL Database available in the market because of its built-in speed boosting technologies, e.g. multi-thread, concurrent backup to multiple destinations, In-File Delta block-level incremental hot backup, configurable compression, etc. You also try this software . Thanks. Leaving a link below just check.http://www.ahsay.com/jsp/en/home/index.jsp?pageContentKey=ahsay_products_overview
