### ISSUE TITLE
Re-release calendar 1.4.1 on apps.owncloud.com with a valid signature

### ISSUE THREAD

**Issue by ghost** [owncloud/calendar#800]
After https://github.com/owncloud/core/pull/27946 was included in oC 9.1.6 ``a Certificate has been revoked`` integrity warning is triggered on oC 9.1.6 with the calendar app published by the "ownCloud" account at https://apps.owncloud.com/content/show.php/Calendar?content=168707

**Comment by PVince81** [comment]
@DeepDiver1975 can you take care ?

**Comment by DeepDiver1975** [comment]
As discussed/advertise on central.owncloud.org - we will support owncloud 9.1 with the new marketplace.
Let me explain how this *experimental* approach will work:
- add this to config.php:
```php
  'appstoreurl' => 'https://marketplace.owncloud.com/api/v0',
```
- open the apps menu and the categories and apps as available on the marketplace will show up - calendar 1.4.2 as well
![bildschirmfoto von 2017-06-01 11-57-01](https://cloud.githubusercontent.com/assets/1005065/26674695/883baae6-46c1-11e7-9714-41dc62e8535f.png)

**Comment by michaelof** [comment]
Hi DeepDiver1975 ,

I've got the same "Certificate has been revoked" msg after upgrading OC to 9.1.6 on OpenSuse Leap 42.2, official rpms from  http://download.owncloud.org/download/repositories/stable/openSUSE_Leap_42.2

Followed your suggestion by adding  'appstoreurl' => 'https://marketplace.owncloud.com/api/v0', to config.php and can see now Calendar 1.4.2 below Apps/Productivity.

BUT if I try to enable, I'm getting an error message "Das Applikationsverzeichnis existiert bereits" (application directory already exists). Both if 1.4.1 is enabled or disabled.

Two short questions:

1) As I don't want to loose my calendar entries: Should/Must/Can I uninstall 1.4.1 and install 1.4.2 *** without *** loosing data? To avoid the  "application directory already exists" error msg?

2) After adding  the  'appstoreurl' to config.php, "calendar 1.41", "contacts 1.51" and "tasks 0.9.4" are now showing up as "experimental", not as "geprüft" (approved) anymore. Expected behaviour?


Kind regards,
Michael 

P.S.: It seems that the error msg "Certificate has been revoked" has disappeared now, maybe by just adding ''appstoreurl'', even without upgrading calendar to 1.4.2. Mysterious :-)

**Comment by mufasa1976** [comment]
After adding ``'appstoreurl' => 'https://marketplace.owncloud.com/api/v0',`` to ``config.php``
no apps are available under Apps/Productivity.

First I had to remove the File ``/path/to/owncloud/data/htaccesstest.txt`` because of error-messages within the webserver log file.

But still no Apps are showing. What have I done wrong? What Information do you need?

**Comment by mikaeldo** [comment]
@michaelof - I ran into exactly the same problem:

1. I upgraded oC to 9.1.6.
2. Calendar app's "certificate has been revoked error" appeared.
3. I followed instructions provided by @DeepDiver1975 - I added a line mentioned above in config.php
4. I could not enable Calendar 1.4.2, because of "directory already exists" error

I did a backup, uninstalled Calendar 1.4.1, and that allowed me to install 1.4.2. I did not need to recover any data from backup. All calendars were there. All looks good.

I hope that helps.

**Comment by localguru** [comment]
Hi, this problem seems to hit a lot people:

https://apps.owncloud.com/content/show.php?content=168707&forumpage=8

And see

https://github.com/nextcloud/calendar/issues/498#issuecomment-306320970

**Comment by pau1ie** [comment]
I have hit this issue on the stable release channel. I upgraded to owncloud 9.0.10 yesterday, and the calendar application (1.4.1) will not enable due to this error.

Can we have some information on how to work around this problem so we can access our calendars? I note from the previous comment that the advice to contact the apps developer doesn't seem to work in this case.

Also, the workaround mentioned above - using the experimental marketplace for 9.1 doesn't work as the apps aren't compatible with 9.0.

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)
```

**Comment by localguru** [comment]
OC 9.0 (Upgrade from 8.2 to 9.0)

I removed ./apps/calendar on filesystem, downloaded the version offered on 

https://apps.owncloud.com/content/show.php/Calendar?action=content&content=168707

and unpacked it under ./apps.

The calendar is working, but there is still the "Certificate has been revoked" problem. Temporarily  I disabled the integrity check in config.php until this is fixed:

```
  'integrity.check.disabled' => true,
```

**Comment by Nokkfried** [comment]
Updating from 9.1.5 to 9.1.6 made it impossible to activate the calendar again.
I followed the recommendation of DeepDiver1975.
Modifying the config and using the new Appstore and installing calendar 1.4.2 worked fine for me.
All my calendar data is still there.
THX.

**Comment by jochenwezel** [comment]
I also ran into the same error after updating from 9.1.6 to v10.0.2 using
```bash
sh -c "echo 'deb http://download.owncloud.org/download/repositories/10.0/Ubuntu_16.04/ /' > /etc/apt/sources.list.d/owncloud.list"
apt-get update
apt-get install owncloud-files
```

Is it possible to automatically update the calendar to v1.4.2 on owncloud 10 update since calendar v1.4.2 is a required update for owncloud 10 to work (to not show any errors)?
For my tested instance, apps "calendar" and "documents" had been deactivated in the apps list, but caused the warning mentioned above.
Alternatively if the app is already deactivated before the upgrade, it might make sense to just drop those obsolete apps?

**Comment by DominicWrege** [comment]
I cant install the Calendar App v 1.4.1

![screen shot 2017-06-07 at 18 57 33](https://user-images.githubusercontent.com/7389000/26890836-45ffdc32-4bb3-11e7-9247-07ed1aa8bdb4.png)

**Comment by Nokkfried** [comment]
Had the same problem, see initial guide from DeepDiver1975 how to install calendar 1.4.2.

**Comment by tony5** [comment]
if you have issues try restarting your webserver.

**Comment by argon3030** [comment]
@mufasa1976  I had the exact same problem of nothing appearing under "Productivity" after adding the new marketplace to config.php.  I had disabled and uninstalled Calendar 1.4.1.  I tried restarting httpd as suggested by @tony5 but that had no effect.  I'm running oC 9.1.6 on CentOS 7.3.

The solution for me was a reboot of the machine, and then it worked perfectly.  Not sure which specific service(s) needed a restart, but bouncing the whole VM did the trick.  I saw all the new marketplace categories like in @DeepDiver1975 screenshot, with Calendar 1.4.2 listed under productivity.  I enabled it, and it worked.  All my existing user's calendar data was still there, and the "certificate revoked" error is no longer present.

**Comment by mehturt** [comment]
I too received this error after upgrading to 9.0.10.  Does the marketplace experimental thing work with OC 9.0.x? The original report was against 9.1.x, hence my question. Thanks.

**Comment by chaffra** [comment]
I am getting the error below when following the instruction for the new app store.

> Server error response [url] http://marketplace.owncloud.com/api/v1/apps/calendar/1.4.2 [status code] 504 [reason phrase] Gateway Timeout

**Comment by localguru** [comment]
@tony5 I removed ```'integrity.check.disabled' => true,``` and restated the complete server. After that the integrity error came back:

```
# sudo -u www-data php occ integrity:check-app calendar
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Certificate has been revoked.
```

**Comment by lordyavin** [comment]
I get 404 for 'https://marketplace.owncloud.com/api/v0'. Damn it. Please more elaborateness. So this approach doesn't work anymore!!

Where can I find correct and up-to-date documentation about the API endpoints?

**Comment by ervee** [comment]
As @mehturt already asked, is there a solution for 9.0.10 ? It is not end-of-life yet but the calendar app got broken by a minor update. If disabling the integrity check is the recommended solution, please state so. I hope there is a better solution though.

**Comment by localguru** [comment]
Sorry for the hard words, but this is a annoying bug and I can't believe that is wasn't fixed for such a long time. The calendar and contacts apps are basic features for a lot users. Not having access to own calendar data is a big no go and tends me to move to nextcloud.

**Comment by DeepDiver1975** [comment]
> I get 404 for 'https://marketplace.owncloud.com/api/v0'. Damn it. Please more elaborateness. So this approach doesn't work anymore!!

This approach works for sure - if you want to check the availability of the api use a correct url - e.g. https://marketplace.owncloud.com/api/v0/content/categories?version=9x1x4x0

**Comment by DeepDiver1975** [comment]
> After that the integrity error came back:

you need to update the app as states above. the certificate for older version of the calendar app has been revoked. Please try to update as stated above.

**Comment by ervee** [comment]
Hi @DeepDiver1975. Is the solution available for 9.0.10 ?

**Comment by DeepDiver1975** [comment]
> Hi @DeepDiver1975. Is the solution available for 9.0.10 ?

I did no yet test myself but I'd say yes. Give it a try and let us know

**Comment by smartissimo** [comment]
> Please try to update as stated above.

Does not work for me neither: "Beim Aktivieren der App ist ein Fehler aufgetreten" - _("An error occurred while activating the app")_

**Comment by DeepDiver1975** [comment]
> Does not work for me neither: "Beim Aktivieren der App ist ein Fehler aufgetreten" - ("An error occurred while activating the app")

please have a look in the owncloud.log - thx

**Comment by CraigInches** [comment]
Steps to resolve on Debian 9.0 after upgrade.
1. php7.0 was installed after upgrade, so using update-alternatives to switch default to php5
2. Disable maintenance mode (due to php upgrade normal steps did not work correctly)
3. Update config with new marketplace url
4. Disable apps (calendar/contacts)
5. Uninstall apps
6. Install New apps from app store
This resolved the certificate error, and integrity check.

**Comment by mufasa1976** [comment]
@argon3030 you're right, after a whole restart i can see the entries under productivity. And also the Calendar App v1.4.2.

But when I try to enable this App I will get a HTTP 502 Bad Gateway.
Here is the Log-Entry from ``owncloud.log``:
```
{
  "reqId":"WUguMHu2q6I8V2ubwWVJnAAAAAc",
  "remoteAddr":"84.115.206.72",
  "app":"core",
  "message":"Server error response [url] https:\/\/storage.marketplace.owncloud.com\/apps\/calendar-1.4.2.tar.gz?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=8BXV1F3LCCSC9Z946NYU%2F20170619%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170619T200702Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=2d2abfe3d5a53ab420ab122ec4383863b37856e1d3b35449591bff4010bc6484 [status code] 502 [reason phrase] Bad Gateway",
  "level":3,
  "time":"2017-06-19T20:08:17+00:00",
  "method":"POST",
  "url":"\/index.php\/settings\/ajax\/enableapp.php",
  "user":"mufasa1976"
}
```

**Comment by DeepDiver1975** [comment]
@tboerger are we facing infra issues at the moment?

**Comment by ghost** [comment]
That bad gateway thingy seems to be fixed now: https://github.com/owncloud/marketplace-issues/issues/6

**Comment by tflidd** [comment]
> Hi @DeepDiver1975. Is the solution available for 9.0.10 ?
> 
> I did no yet test myself but I'd say yes. Give it a try and let us know

@DeepDiver1975 It doesn't work for OC 9.0.10! It says:
`No apps found for your version`


The download link in https://marketplace.owncloud.com/apps/contacts does not work either, so a manual install is not possible.

I tried to install the 1.5.2 release from the github archive, it installs, makes an update but then there are several errors like this one:
```
Could not find resource file \"\/owncloud\/apps\/contacts\/js\/vendor\/angular-cache\/dist\/angular-cache.js
```

> we will support owncloud 9.1 with the new marketplace.
> Let me explain how this experimental approach will work:

Are you joking? People use OC 9.0 or 9.1 because they want a stable release of OC. Then you revoke a certificate which breaks a minor upgrade and force people to use an experimental approach for the app store?

I understand the rivalry with Nextcloud but such issues are the best advertisement for Nextcloud.

**Comment by localguru** [comment]
@CraigInches what's happens on uninstall with calendar data? removed?

**Comment by CraigInches** [comment]
@localguru No all my data was still there.

**Comment by DeepDiver1975** [comment]
> Are you joking?

no

**Comment by ervee** [comment]
So @tflidd tried the suggested steps by @DeepDiver1975 and it did not work. I have no test/dev envoronment to test this a.t.m. so I'm not burning my hands on it (again).

@DeepDiver1975, is there by any chance a way you could fix this for all the people still the OC9.0 please?

**Comment by DeepDiver1975** [comment]
> The download link in https://marketplace.owncloud.com/apps/contacts does not work either, so a manual install is not possible.

This is working ... 
![screencast_27 06 2017_22_02_52](https://user-images.githubusercontent.com/1005065/27607628-ca9ae9c4-5b84-11e7-939b-a563978df669.gif)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975, is there by any chance a way you could fix this for all the people still the OC9.0 please?

As explained above I did not test 9.0 myself yet - I'll take care asap. An official statement on this will follow.

**Comment by tflidd** [comment]
Little update:

- Today I can connect to the app store via my owncloud, I can find a few apps (audio player in multimedia, roundcube in productivity, and 4 other apps in Tools. There is no calendar or contact app.
- The marketplace is now offering a download, yesterday I only got a 404 error.
- I managed to download and install a new contact app manually. There is still a problem, I will post it in the contacts repo, I posted my problems in the wrong app-repo (though the problems are related). -> **update:** Clearing the Browser cache solved the problem (didn't show all contacts).

**Comment by DeepDiver1975** [comment]
> I can find a few apps (audio player in multimedia, roundcube in productivity, and 4 other apps in Tools.

but this sounds like you are connected to the old appstore - on the marketplace there is no roundcube ...



> The marketplace is now offering a download, yesterday I only got a 404 error.

🙈 



> I managed to download and install a new contact app manually. There is still a problem, I will post it in the contacts repo, I posted my problems in the wrong app-repo (though the problems are related).

👍

**Comment by mufasa1976** [comment]
After the Owncloud Marketplace has be re-enabled by @tboerger the solution described by @DeepDiver1975 in combination with the hint by @localguru (remove the directory ``apps/calendar``) worked like a charme.

**Comment by ghost** [comment]
> An official statement on this will follow.

-> https://owncloud.org/blog/good-bye-apps-owncloud-com/

@DeepDiver1975 I guess we can close this one or do you want to keep this open and update the old calendar app at apps.owncloud.com?

**Comment by larsrh** [comment]
For everyone who is running Owncloud on shared hosting and restarting the server doesn't work: A method of "last resort" is to go to `lib/private/integritycheck/checker.php` and just returning `false` in function `isCodeCheckEnforced`. _I do not recommend that for a public installation or anything that is accessed by more than one user!_

**Comment by AlexandreBonneau** [comment]
To complete @mikaeldo [comment](https://github.com/owncloud/calendar/issues/800#issuecomment-305962078),

1. I upgraded oC to 9.1.6.
2. Calendar app's "certificate has been revoked error" appeared.
3. I followed instructions provided by @DeepDiver1975 [here](https://github.com/owncloud/calendar/issues/800#issuecomment-305447367) and added the line `'appstoreurl' => 'https://marketplace.owncloud.com/api/v0',` in the `config/config.php` file.
4. Then in the admin applications screen I tried activating the Calendar app, but it failed saying the directory already existed
5. At this point, **BACKUP** your data (in `/var/www/owncloud` and with a `mysqldump -u root -p owncloud >> ~/owncloud_db_save.sql`)
6. Backup is done, right?
7. `cd /var/www/owncloud/apps`, `mv calendar calendar_old` (do that for the other apps like contacts too)
8. Click Activate in the admin application screen for the new calendar app
9. Once it's installed, you can check that there is a new `/var/www/owncloud/apps/calendar` directory, and refreshing the calendar page will show it to you
10. After checking that everything is fine, you can delete the `calendar_old` directory and its content safely.
11. 🎉 

All good indeed.

**Comment by ghost** [comment]
@AlexandreBonneau Nice write-up 👍 

There is now also a note about deleting the old app directory (step 7.) since a few days at https://owncloud.org/blog/good-bye-apps-owncloud-com/ based on https://github.com/owncloud/owncloud.org/issues/1245
