### ISSUE TITLE
http instead of https on caldav link

### ISSUE THREAD

**Issue by PopovK** [owncloud/calendar#886]
When using the "get caldav link" on a calendar, the generated link in the textbox with autoselect on mouseover always states "http://..."
Even on a https connection on the server.

Also, the textbox should be read only, write input is currently allowed

Same http:// anomaly on the "Primary Caldav address" and "IOS/OSX Caldav address" in the cog panel at bottom

owncloud 8.1.0, https enforced with htaccess redirect.

**Comment by RealRancor** [comment]
Try to set https://github.com/owncloud/core/blob/v8.1.0/config/config.sample.php#L349-L356 to https

**Comment by PopovK** [comment]
Using this setting fixes it, thanks.
But it's worth knowing the owncloud I use isn't behind a proxy, it's a direct access.

**Comment by RealRancor** [comment]
Is the URL on https://yourdomain/index.php/apps/files -> Cogwheel bottom left -> WebDAV also http:// instead of https:// (you need to remove the config.php entry above for testing)?

If yes then you might want to close here and re-open in:

https://github.com/owncloud/core/issues

using the issue template provided here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version (That one should be always used when creating new issues).

**Comment by PopovK** [comment]
Yup, just checked, there's the same behavior on the Webdav link, show http on a https connection

**Comment by georgehrke** [comment]
please reopen as @RealRancor asked, thanks :)
