### ISSUE TITLE
Display week number in web view

### ISSUE THREAD

**Issue by jas4711** [owncloud/calendar#929]
It would be nice if the calendar web app showed the week number.  Alternatively, add an option to display it, if you don't want to make it the default.  If you make it unobtrusive, I think it would be acceptable to display it by default.

(The background for this request is that at least in Sweden, scheduling is commonly done by talking about week number of the year.)

**Comment by georgehrke** [comment]
This has to be implemented upstream. Could you please open a pull request at https://github.com/arshaw/fullcalendar :)

**Comment by jas4711** [comment]
Fullcalendar already supports week numbers, see one of their examples: http://fullcalendar.io/js/fullcalendar-2.4.0/demos/languages.html

You are using fullcalendar 1.6.4 (at least that is what 3rdparty/fullcalendar/js/fullcalendar.min.js says), any chance you could update to latest 2.6.4?

**Comment by georgehrke** [comment]
we'll update, but not before ownCloud 9

**Comment by peternowee** [comment]
+1 for the feature request.

I have been looking into this issue recently as well and found that two years ago, in issue #157, the following comments were made regarding the display of week numbers:

> [T]here should not be an extra column for week numbers. At most a small grey »Week 32« indicator on the top left of the first day of the week or so. -- @jancborchardt on 3 Oct 2013
 
> I agree with @jancborchardt that it should be done like in OS X's calendar app: [image of calendar with week number in top left of first day of the week] -- @georgehrke on 3 Oct 2013

Currently, FullCalendar still uses the extra column. AFAICT, there is no option for display in the top left of the first day, nor has any such feature been requested in their issue list.

@georgehrke and @jancborchardt : Considering that [feature requests for FullCalendar might take a while to make it to an official release] [1], is the display of the week numbers in a separate column still a blocker for you? Because if it is, an issue/feature request might as well be filed with FullCalendar now already. I am willing to do that, but would like to hear your thoughts first.

[1]: https://github.com/fullcalendar/fullcalendar/blob/master/CONTRIBUTING.md#contributing-features

**Comment by jancborchardt** [comment]
@peternowee I’d like to give the calendar as much screen space as possible. That’s why a different column is not a great solution. If it can be styled in a way that it’s just part of the first-day-of-week-field or somewhere else on the left side, it’s much better.

**Comment by peternowee** [comment]
Ok, I opened an issue upstream: fullcalendar/fullcalendar#2941.

@georgehrke: Perhaps this issue (owncloud/calendar#929) can be re-opened?

**Comment by peternowee** [comment]
@georgehrke @jancborchardt I think I'm finished with the necessary FullCalendar changes. Perhaps you can have a look at it at:

https://github.com/peternowee/fullcalendar/commits/weeknr-in-daycell 

It's a few commits, so you will probably want to checkout the entire branch. Then use the options `weekNumbers: true` and `basicViewWeekNrPosition: weekNrDayCell` to see it work.

I will await your responses before sending a pull request to FullCalendar.

**Comment by peternowee** [comment]
@georgehrke @jancborchardt 

For your convenience, I made a fork of calendar-rework to show the changes I propose for FullCalendar: https://github.com/peternowee/calendar-rework/tree/test-fc-weeknr

Screenshot (German):
![oc fc weeknr-in-daycell deutsch german](https://cloud.githubusercontent.com/assets/10220583/12643765/68beae78-c5be-11e5-9ed5-443e98ebc256.png)

Screenshot (US English):
![oc fc weeknr-in-daycell us english](https://cloud.githubusercontent.com/assets/10220583/12643767/6b7d2cfc-c5be-11e5-9126-36778208ec01.png)

I noticed the border of the highlighted day being overlapped by the day number. This is probably caused by changes in the HTML classes. The day numbers and their class `fc-day-number` were moved from their own `td` element to a new `span` within that `td`. The `td` got class `fc-numbercell` instead and can contain `span` elements for `fc-day-number` and `fc-week-number`. These changes may require some CSS changes to solve the border overlap.

Awaiting your comments.

Cc @raghunayyar

**Comment by jancborchardt** [comment]
@peternowee nice! It should always be lighter than the day number though because otherwise that’s confusing. Like 25 % opacity for the active month, and even less for when inactive (like the day number is lighter too).

**Comment by peternowee** [comment]
@jancborchardt Ok, here is a screenshot with 25% opacity:

![20160129 oc 2a88528 fc 9b364fe css opacity 0 25 weeknr-in-daycell deutsch german](https://cloud.githubusercontent.com/assets/10220583/12675301/870578b4-c689-11e5-85a7-16d2c1875fb2.png)

As an alternative, here is a screenshot similar to OS X's calendar app screenshot from https://github.com/owncloud/calendar/issues/157#issuecomment-25627615 :

![20160129 oc 2a88528 fc 9b364fe css round corner weeknr-in-daycell deutsch german](https://cloud.githubusercontent.com/assets/10220583/12675294/819e8ab4-c689-11e5-8619-15b3a6736b4f.png)

As you can see, I fixed the border issue as well. Let me know which one you prefer.

Btw, do you think I should still wait for replies of @georgehrke and @raghunayyar before sending a pull request to FullCalendar?

@jas4711 Are you able to re-open this issue?

**Comment by jancborchardt** [comment]
@peternowee can you do another version of the second one with the background, but using a much lighter background? Also, the border-radius should be 3px, as elsewhere in ownCloud. :) Then I think it would be cool.

Also, we do have a setting for »Show week number«, off by default, right? @georgehrke @raghunayyar?

**Comment by georgehrke** [comment]
> can you do another version

in calendar-rework please. ;)

> we do have a setting for »Show week number«

There is no setting at the moment. Do we need one?

**Comment by peternowee** [comment]
I didn't see such a setting yet in ownCloud. I thought about starting on that after sending the PR to FullCalendar.

**Comment by peternowee** [comment]
My branch https://github.com/peternowee/calendar-rework/tree/test-fc-weeknr is based on calendar-rework.

I will make the CSS changes to the background and radius and then push the commit for that to that branch as well.

**Comment by jancborchardt** [comment]
@georgehrke yes, I would do a setting for that, off by default. Because I’d say most people actually do not need week numbers.

**Comment by peternowee** [comment]
Like this?

![2016-01-29-160525_1366x768_scrot](https://cloud.githubusercontent.com/assets/10220583/12679171/fb7ae3be-c6a2-11e5-9f51-b7a5a8ae45d5.png)

**Comment by georgehrke** [comment]
I like it :)

**Comment by jancborchardt** [comment]
Yeah, looks good! :)

**Comment by peternowee** [comment]
Ok, I updated https://github.com/peternowee/calendar-rework/tree/test-fc-weeknr accordingly. Do you still want to have a look at the technical side of the implementation?

Then one more thing I almost forgot: Day and Week views. The default formatting is like this:

![2016-01-29-164051_1366x768_scrot](https://cloud.githubusercontent.com/assets/10220583/12680761/d1db6c6e-c6ab-11e5-8122-bc6fb0b7cfa8.png)

So, FullCalendar shows the week number in the top left corner and I wouldn't want to request them to change that only for us. We can easily change or remove the preceding letter (W). It could probably even be made locale-dependent, but I am not interested in spending my time on that. So my suggestion is to remove the preceding letter and use a similar formatting as in the Month view to make clear that this is a week number:

![2016-01-29-170754_1366x768_scrot](https://cloud.githubusercontent.com/assets/10220583/12680757/cfb4bb48-c6ab-11e5-96e2-b3b9ed884a7f.png)

What do you think?

**Comment by peternowee** [comment]
The formatting in Day and Week view can be done in our own stylesheet, btw, so no change required in FullCalendar.

**Comment by georgehrke** [comment]
I would actually go with the default style here.

**Comment by peternowee** [comment]
Ok, I created a pull request upstream: https://github.com/fullcalendar/fullcalendar/pull/3024. Thanks for all your comments so far!

**Comment by jas4711** [comment]
@peternowee sorry i don't seem to be able to re-open the issue, maybe @georgehrke could?

Many thanks for working on this!  I really mis seeing week numbers.  In Sweden a lot of activity planning is done around week numbers.  I have imported a separate calendar with week numbers as a workaround, but it is a really ugly solution.

**Comment by peternowee** [comment]
@jas4711 Yeah, I know, hope the new changes get accepted upstream soon. Thanks for replying.

**Comment by georgehrke** [comment]
Let's not reopen this, if anything please create an issue in https://github.com/owncloud/calendar-rework

**Comment by peternowee** [comment]
Ok, I will send a PR to calendar-rework later.
